# This file was generated by GoReleaser. DO NOT EDIT.
cask "eggl-cli" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "9ebdcf70889e64672edf75f3b916de230967458e7dd617b64d7234310b570725"
      url "https://github.com/Robert27/eggl-cli/releases/download/v#{version}/eggl-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "89ba377b417743b2bc9d5be4036a8e3d8108e41a7a7a9a5992ecd3e9a02fa4ec"
      url "https://github.com/Robert27/eggl-cli/releases/download/v#{version}/eggl-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2ef5294d35ce060bbbb65bc384f8c163cb65b63b2e92a6a2833175ee6c9ea535"
      url "https://github.com/Robert27/eggl-cli/releases/download/v#{version}/eggl-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5846c7849337160cebfc9b8cc3bfb9cbd6de48f508ebc184b9b34d001272217d"
      url "https://github.com/Robert27/eggl-cli/releases/download/v#{version}/eggl-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "eggl-cli"
  desc "General-purpose helper CLI"
  homepage "https://github.com/Robert27/eggl-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "eggl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/eggl"]
    end
  end

  # No zap stanza required

end
