# This file was generated by GoReleaser. DO NOT EDIT.
cask "eggl-cli" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "811d95cbb5150af6713905047b4ae21bb8ac379f1307b6c157de55c66fa225cb"
      url "https://github.com/Robert27/eggl-cli/releases/download/v0.1.0/eggl-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4314f56991f12fdf4422309fe66bae014f8a09332fb61282ee91c6a68ae024d4"
      url "https://github.com/Robert27/eggl-cli/releases/download/v0.1.0/eggl-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "90db8b77ae97d7cd6bfcfa4e42027d732388a3d660c0a1d83a1c82b6e722753a"
      url "https://github.com/Robert27/eggl-cli/releases/download/v0.1.0/eggl-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cac0b101220ca814a8108457a60e80b808855c7c106585ffd6b1826b23deeb02"
      url "https://github.com/Robert27/eggl-cli/releases/download/v0.1.0/eggl-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "eggl-cli"
  desc "General-purpose helper CLI"
  homepage "https://github.com/Robert27/eggl-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "eggl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/eggl"]
    end
  end

  # No zap stanza required

end
