# This file was generated by GoReleaser. DO NOT EDIT.
cask "eggl-cli" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "b65594835e997fccb10156f46036359b0b0e4825f48b076b56567dac50f10857"
      url "https://github.com/Robert27/eggl-cli/releases/download/v#{version}/eggl-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9f20fbde5f77ead3eab40ebf56c7a5e2d465aea8f80169c11a92e2f12105be1c"
      url "https://github.com/Robert27/eggl-cli/releases/download/v#{version}/eggl-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5e301e8fd082597ca57bbb7707ad90f1cd556ca2f1d6b7b874a08517c4e40740"
      url "https://github.com/Robert27/eggl-cli/releases/download/v#{version}/eggl-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d6c252d991b6a1613c5ca0e32b8adf511f460261ff297ff882d19bb8aacd30d6"
      url "https://github.com/Robert27/eggl-cli/releases/download/v#{version}/eggl-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "eggl-cli"
  desc "General-purpose helper CLI"
  homepage "https://github.com/Robert27/eggl-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "eggl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/eggl"]
    end
  end

  # No zap stanza required

end
