# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EgglCli < Formula
  desc "General-purpose helper CLI"
  homepage "https://github.com/Robert27/eggl-cli"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Robert27/eggl-cli/releases/download/v0.4.1/eggl-cli_0.4.1_darwin_amd64.tar.gz"
      sha256 "5d2746bd0c69a1e6d30e94239adb276a3eadfb5aae1afb8a1e4f79424ebf0995"

      define_method(:install) do
        bin.install "eggl"
        generate_completions_from_executable(bin/"eggl", shells: [:bash, :zsh, :fish], shell_parameter_format: :cobra)
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Robert27/eggl-cli/releases/download/v0.4.1/eggl-cli_0.4.1_darwin_arm64.tar.gz"
      sha256 "066de1338542ae3bdd03d63d6932f75daa8c62678e0d68573f3fd56c4dd842fb"

      define_method(:install) do
        bin.install "eggl"
        generate_completions_from_executable(bin/"eggl", shells: [:bash, :zsh, :fish], shell_parameter_format: :cobra)
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Robert27/eggl-cli/releases/download/v0.4.1/eggl-cli_0.4.1_linux_amd64.tar.gz"
      sha256 "9877b40ee5dc203338714215755cbc895a54cab8fb9a2e0c03e14f1d4f2be332"
      define_method(:install) do
        bin.install "eggl"
        generate_completions_from_executable(bin/"eggl", shells: [:bash, :zsh, :fish], shell_parameter_format: :cobra)
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Robert27/eggl-cli/releases/download/v0.4.1/eggl-cli_0.4.1_linux_arm64.tar.gz"
      sha256 "8505383d348ade48bcf05a03ce8c3faecc4b4027c6d2a7b276a88a2761d061b6"
      define_method(:install) do
        bin.install "eggl"
        generate_completions_from_executable(bin/"eggl", shells: [:bash, :zsh, :fish], shell_parameter_format: :cobra)
      end
    end
  end

  def post_install
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{bin}/eggl"], sudo: false
    end
  end
end
