# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EgglCli < Formula
  desc "General-purpose helper CLI"
  homepage "https://github.com/Robert27/eggl-cli"
  version "0.9.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Robert27/eggl-cli/releases/download/v0.9.1/eggl-cli_0.9.1_darwin_amd64.tar.gz"
      sha256 "9ac835f69e4fca91479944b87015df540e1d1b76e30f58a955f020161458f5d9"

      define_method(:install) do
        bin.install "eggl"
        generate_completions_from_executable(bin/"eggl", shells: [:bash, :zsh, :fish], shell_parameter_format: :cobra)
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Robert27/eggl-cli/releases/download/v0.9.1/eggl-cli_0.9.1_darwin_arm64.tar.gz"
      sha256 "7bed599a917babcd053c23a9d2d74e2165bf56c1c8a0cc5da4df0e26ac6e9f5c"

      define_method(:install) do
        bin.install "eggl"
        generate_completions_from_executable(bin/"eggl", shells: [:bash, :zsh, :fish], shell_parameter_format: :cobra)
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Robert27/eggl-cli/releases/download/v0.9.1/eggl-cli_0.9.1_linux_amd64.tar.gz"
      sha256 "226a9d5b0bd6a4487e425d039e8fb9762bd6e63c59b2d2d1360d2784a03251d1"
      define_method(:install) do
        bin.install "eggl"
        generate_completions_from_executable(bin/"eggl", shells: [:bash, :zsh, :fish], shell_parameter_format: :cobra)
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Robert27/eggl-cli/releases/download/v0.9.1/eggl-cli_0.9.1_linux_arm64.tar.gz"
      sha256 "948d2a3a4728d0c792cee6f942181619afb412b731b5df9632a46fc2dce89be5"
      define_method(:install) do
        bin.install "eggl"
        generate_completions_from_executable(bin/"eggl", shells: [:bash, :zsh, :fish], shell_parameter_format: :cobra)
      end
    end
  end

  def post_install
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{bin}/eggl"], sudo: false
    end
  end
end
