# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EgglCli < Formula
  desc "General-purpose helper CLI"
  homepage "https://github.com/roberteggl/eggl-cli"
  version "0.11.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/roberteggl/eggl-cli/releases/download/v0.11.0/eggl-cli_0.11.0_darwin_amd64.tar.gz"
      sha256 "01094e276fe657651749b8bead5d92ae744d894b5f0955958e3ff10b1b59d3d7"

      define_method(:install) do
        bin.install "eggl"
        generate_completions_from_executable(bin/"eggl", shells: [:bash, :zsh, :fish], shell_parameter_format: :cobra)
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/roberteggl/eggl-cli/releases/download/v0.11.0/eggl-cli_0.11.0_darwin_arm64.tar.gz"
      sha256 "fecce095a677f84189371e4f450cdac2573181670923aa5d640bede2466114ee"

      define_method(:install) do
        bin.install "eggl"
        generate_completions_from_executable(bin/"eggl", shells: [:bash, :zsh, :fish], shell_parameter_format: :cobra)
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/roberteggl/eggl-cli/releases/download/v0.11.0/eggl-cli_0.11.0_linux_amd64.tar.gz"
      sha256 "ae4cd1cf89ab49f7a6313de629d8be8411fa8994ccb7b22195be4c13a8d81e83"
      define_method(:install) do
        bin.install "eggl"
        generate_completions_from_executable(bin/"eggl", shells: [:bash, :zsh, :fish], shell_parameter_format: :cobra)
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/roberteggl/eggl-cli/releases/download/v0.11.0/eggl-cli_0.11.0_linux_arm64.tar.gz"
      sha256 "76411a2f78fe729e9ad0c18d57a8d82ae0edf858597c0d7a9be3ac932b775998"
      define_method(:install) do
        bin.install "eggl"
        generate_completions_from_executable(bin/"eggl", shells: [:bash, :zsh, :fish], shell_parameter_format: :cobra)
      end
    end
  end

  def post_install
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{bin}/eggl"], sudo: false
    end
  end
end
